[build]
  base = "/frontend" # Set the working directory to /frontend
  command = "npm i --force && npm run build && npm run export" # Use next export instead of next build
  publish = "/out" # Set the directory to publish (output of the export)
